# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y3dBs-ik8mTRL7dEL2A-qnB14_fFWHcb
"""

import random
user_wins =0
computer_wins =0
options = ["rock","paper","scissors"]

while True:
  user_input = input("Type Rock/Paper/Scissor or Q to quit : " ).lower()
  if user_input =="q":
    break

  if user_input not in options:
    continue

  random_number = random.randint(0,2)
  # rock:0 ,paper:1 ,scissors:2
  computer_pick = options[random_number]
  print("computer picked",computer_pick +".")

  if user_input == "rock" and computer_pick =="scissors":
    print("You won!")
    user_wins+=1

  elif user_input == "paper" and computer_pick =="rock":
    print("You won!")
    user_wins+=1

  elif user_input == "scissors" and computer_pick =="paper":
    print("You won!")
    user_wins+=1

  elif user_input == computer_pick:
    print("Draw")

  else:
    print("You lost!")
    computer_wins+=1

print("you won",user_wins,'times')
print("computer won",computer_wins,'times')

if user_wins>computer_wins:
  print("You are the winner")
elif user_wins<computer_wins:
  print("computer is the winner")
else:
  print("Match Draw")
print("Goodbye!")